---

- name: Playbook for Installing DOMjudge on a Debian Server. Should be executed on the Host Server!
  hosts: controller
  become: yes

  vars_prompt:
    - name: username
      prompt: "Enter a username to create a user fo Domjudge"
      private: no
    - name: user_password
      prompt: "Please enter your password for the Domjudge user"
      private: yes

  vars_files:
    - vault.yml

  roles:
    - role: common
    - role: domjudge-user
    - role: domjudge-server-build
    - role: domjudge-db
    - role: domjudge-web
    - role: domjudge-judgehost-build
    - role: domjudge-judgedaemon


  tasks:
    - name: Reset admin user password
      ansible.builtin.shell: 
        cmd: ./bin/console domjudge:reset-user-password admin
        chdir: "{{ domjudge_install_path }}/webapp"
      register: shell_output
      become_user: "{{ username }}"
      no_log: true

    - name: Show the password
      ansible.builtin.debug:
        msg: "{{ shell_output.stdout | split ('[OK]') | last | trim }}"
