---

- name: Test single role
  hosts: 192.168.224.138
  become: yes
  
  vars_prompt:
    - name: username
      prompt: "Enter a username to create a user fo Domjudge"
      private: no
    - name: user_password
      prompt: "Please enter your password for the Domjudge user"
      private: yes

  vars_files:
    - vault.yml

  roles:
    - role: domjudge-judgehost-build
    - role: domjudge-judgedaemon 
