---
# Creates the Domjudge Database and configures the Database

- name: Ensure MariaDB is installed
  ansible.builtin.package:
    name: mariadb-server
    state: present
  become: true

- name: Ensure MariaDB is running
  ansible.builtin.service:
    name: mariadb
    state: started
    enabled: true
  become: true

- name: Generate database credentials file
  ansible.builtin.command: >
    ./dj_setup_database genpass
  args:
    chdir: /home/{{ username }}/Domjudge/domserver/bin
  become_user: "{{ username }}"

- name: Drop Domjudge Database if it exists
  community.mysql.mysql_query:
    query: "DROP DATABASE IF EXISTS domjudge;"
    login_user: root
    login_password: "{{ db_admin_password }}"
  become: true

- name: Run Domjudge database setup script tp install database and user
  ansible.builtin.command: >
    ./dj_setup_database -u root -p {{ db_admin_password }} install
  args:
    chdir: /home/{{ username }}/Domjudge/domserver/bin
  become: true
